# Backlight
switch:
  - platform: template
    id: backlight
    restore_mode: ALWAYS_ON
    internal: true
    turn_on_action:
      - light.turn_on: display_backlight
    turn_off_action:
      - light.turn_off: display_backlight

# Screensaver Presence Trigger
binary_sensor:
  - platform: homeassistant
    id: presence
    entity_id: binary_sensor.office_presence_group
    on_press:
      - lvgl.resume:
      - delay: 10ms
      - switch.turn_on: backlight
      - logger.log: "Screensaver is turned off"

    on_release:
      - switch.turn_off: backlight
      - lvgl.pause:
          show_snow: true
      - logger.log: "Screensaver is turned on"
