# =============================================================================
# SENSORS - Music dashboard (media_player.office)
# =============================================================================
# Subscribes to media_player attributes and updates LVGL labels, bar, image,
# and play/pause icon. Entity and HA base URL come from substitutions in
# template.yaml (media_player_entity, ha_base_url).
# =============================================================================

text_sensor:
  - platform: homeassistant
    entity_id: ${media_player_entity}
    id: media_title_sensor
    attribute: media_title
    on_value:
      - lvgl.label.update:
          id: media_title_label
          text: !lambda 'return x.empty() ? std::string("—") : x;'
    trigger_on_initial_state: true

  - platform: homeassistant
    entity_id: ${media_player_entity}
    id: media_artist_sensor
    attribute: media_artist
    on_value:
      - lvgl.label.update:
          id: media_artist_label
          text: !lambda 'return x.empty() ? std::string("—") : x;'
    trigger_on_initial_state: true

  - platform: homeassistant
    entity_id: ${media_player_entity}
    id: media_entity_picture_sensor
    attribute: entity_picture
    on_value:
      - if:
          condition:
            lambda: 'return !x.empty();'
          then:
            - online_image.set_url:
                id: album_art_image
                url: !lambda 'return std::string("${ha_base_url}") + std::string(x);'
    trigger_on_initial_state: true

  - platform: homeassistant
    entity_id: ${media_player_entity}
    id: media_player_state_sensor
    on_value:
      - lvgl.label.update:
          id: media_play_pause_icon
          text: !lambda |-
            if (x == "playing") return std::string(u8"\uF03E4");  // mdi-pause
            return std::string(u8"\uF040D");  // mdi-play
    trigger_on_initial_state: true

sensor:
  - platform: homeassistant
    entity_id: ${media_player_entity}
    id: media_duration_sensor
    attribute: media_duration
    on_value:
      - lvgl.label.update:
          id: media_duration_label
          text: !lambda |-
            char buf[12];
            int sec = (int)x;
            if (sec < 0) sec = 0;
            int m = sec / 60;
            int s = sec % 60;
            snprintf(buf, sizeof(buf), "%02d:%02d", m, s);
            return std::string(buf);

  - platform: homeassistant
    entity_id: ${media_player_entity}
    id: media_position_sensor
    attribute: media_position
    on_value:
      - lvgl.label.update:
          id: media_elapsed_label
          text: !lambda |-
            char buf[12];
            int sec = (int)x;
            if (sec < 0) sec = 0;
            int m = sec / 60;
            int s = sec % 60;
            snprintf(buf, sizeof(buf), "%02d:%02d", m, s);
            return std::string(buf);
      - lvgl.bar.update:
          id: media_progress_bar
          value: !lambda |-
            float pos = x;
            float dur = id(media_duration_sensor).state;
            if (dur > 0) {
              return (int)((pos / dur) * 100.0f);
            }
            return 0;
