# =============================================================================
# SENSORS - Music dashboard (media_player.office)
# =============================================================================
# Subscribes to media_player attributes and updates LVGL labels, bar, image,
# and play/pause icon. To use a different entity, override in your main YAML
# with a package override or use a local copy and set entity_id.
# Album art base URL: http://192.168.1.30:8123 (path from HA already includes token).
# =============================================================================

# Store last HA position and time so we can estimate elapsed time between updates
# (HA/Sonos often only push media_position every 5–10s; we tick every 1s)
globals:
  - id: last_media_position
    type: float
    initial_value: '0.0'
  - id: last_position_timestamp
    type: int
    initial_value: '0'

# Refresh progress bar and elapsed time every second; when playing, estimate
# position from last HA update + elapsed time so the clock moves smoothly
interval:
  - interval: 1s
    then:
      - lvgl.label.update:
          id: media_elapsed_label
          text: !lambda |-
            // When last_position_timestamp is 0 (e.g. after skip), use last_media_position so we show 0 until HA sends new position
            float pos = id(last_position_timestamp) != 0 && id(media_position_sensor).has_state()
              ? id(media_position_sensor).state : id(last_media_position);
            if (id(media_player_state_sensor).state == "playing") {
              auto t = id(sntp_time).now();
              if (t.is_valid() && id(last_position_timestamp) != 0) {
                pos = id(last_media_position) + (t.timestamp - id(last_position_timestamp));
                if (pos < 0) pos = 0;
                float dur = id(media_duration_sensor).has_state() ? id(media_duration_sensor).state : 0.0f;
                if (dur > 0 && pos > dur) pos = dur;
              }
            }
            char buf[12];
            int sec = (int)pos;
            if (sec < 0) sec = 0;
            int m = sec / 60;
            int s = sec % 60;
            snprintf(buf, sizeof(buf), "%02d:%02d", m, s);
            return std::string(buf);
      - lvgl.bar.update:
          id: media_progress_bar
          value: !lambda |-
            float pos = id(last_position_timestamp) != 0 && id(media_position_sensor).has_state()
              ? id(media_position_sensor).state : id(last_media_position);
            if (id(media_player_state_sensor).state == "playing") {
              auto t = id(sntp_time).now();
              if (t.is_valid() && id(last_position_timestamp) != 0) {
                pos = id(last_media_position) + (t.timestamp - id(last_position_timestamp));
                if (pos < 0) pos = 0;
                float dur = id(media_duration_sensor).has_state() ? id(media_duration_sensor).state : 0.0f;
                if (dur > 0 && pos > dur) pos = dur;
              }
            }
            float dur = id(media_duration_sensor).has_state() ? id(media_duration_sensor).state : 0.0f;
            if (dur > 0) return (int)((pos / dur) * 100.0f);
            return 0;

text_sensor:
  - platform: homeassistant
    entity_id: media_player.office
    id: media_title_sensor
    attribute: media_title
    on_value:
      # Track changed (skip/next) — reset progress so UI shows 0 until HA sends new position
      - lambda: "id(last_position_timestamp) = 0; id(last_media_position) = 0.0f;"
      - lvgl.label.update:
          id: media_title_label
          text: !lambda 'return x.empty() ? std::string("—") : x;'
      - lvgl.label.update:
          id: media_elapsed_label
          text: "0:00"
      - lvgl.bar.update:
          id: media_progress_bar
          value: 0

  - platform: homeassistant
    entity_id: media_player.office
    id: media_artist_sensor
    attribute: media_artist
    on_value:
      - lvgl.label.update:
          id: media_artist_label
          text: !lambda 'return x.empty() ? std::string("—") : x;'

  - platform: homeassistant
    entity_id: media_player.office
    id: media_entity_picture_sensor
    attribute: entity_picture
    on_value:
      - if:
          condition:
            lambda: 'return !x.empty();'
          then:
            - online_image.set_url:
                id: album_art_background
                url: !lambda |-
                  std::string path = x;
                  while (!path.empty() && (path.back() == '\n' || path.back() == '\r' || path.back() == ' ')) path.pop_back();
                  return std::string("http://192.168.1.30:8123") + path;

  - platform: homeassistant
    entity_id: media_player.office
    id: media_player_state_sensor
    on_value:
      - if:
          condition:
            lambda: 'return x == "playing";'
          then:
            - lvgl.widget.hide:
                id: media_play_icon
            - lvgl.widget.show:
                id: media_pause_icon
          else:
            - lvgl.widget.show:
                id: media_play_icon
            - lvgl.widget.hide:
                id: media_pause_icon

sensor:
  - platform: homeassistant
    entity_id: media_player.office
    id: media_duration_sensor
    attribute: media_duration
    on_value:
      - lvgl.label.update:
          id: media_duration_label
          text: !lambda |-
            char buf[12];
            int sec = (int)x;
            if (sec < 0) sec = 0;
            int m = sec / 60;
            int s = sec % 60;
            snprintf(buf, sizeof(buf), "%02d:%02d", m, s);
            return std::string(buf);

  - platform: homeassistant
    entity_id: media_player.office
    id: media_position_sensor
    attribute: media_position
    on_value:
      - lambda: |-
          id(last_media_position) = x;
          auto t = id(sntp_time).now();
          if (t.is_valid()) id(last_position_timestamp) = t.timestamp;
      - lvgl.label.update:
          id: media_elapsed_label
          text: !lambda |-
            char buf[12];
            int sec = (int)x;
            if (sec < 0) sec = 0;
            int m = sec / 60;
            int s = sec % 60;
            snprintf(buf, sizeof(buf), "%02d:%02d", m, s);
            return std::string(buf);
      - lvgl.bar.update:
          id: media_progress_bar
          value: !lambda |-
            float pos = x;
            float dur = id(media_duration_sensor).state;
            if (dur > 0) {
              return (int)((pos / dur) * 100.0f);
            }
            return 0;
