binary_sensor:
  # Condensate evaporator switch
  - platform: homeassistant
    id: condensate_evaporator_switch
    entity_id: switch.condensate_evaporator_switch
    trigger_on_initial_state: true
    on_state:
      if:
        condition:
          lambda: 'return x;'
      then:
        - logger.log: "Condensate evaportor on"
      else:
        - logger.log: "Condensate evaportor off"
      lvgl.widget.update:
        id: condensate_evaporator_button
        state:
          checked: !lambda return x;