binary_sensor:
  # Condensate evaporator switch position
  - platform: homeassistant
    id: condensate_evaporator_switch
    entity_id: switch.condensate_evaporator_switch
    on_state:
      then:
        lvgl.widget.update:
          id: condensate_evaporator_button
          state:
            checked: !lambda return x;

sensor:
  - platform: homeassistant
    id: ha_temp
    entity_id: sensor.sydney_observatory_hill_temp
    internal: true # Keeps it from being sent back to HA
    on_value:
      then:
        - lvgl.label.update:
            id: temp_label
            text: !lambda |-
              return ("Temp: " + str_sprintf("%.1f", x) + "°C").c_str();

  - platform: homeassistant
    id: ha_rain
    entity_id: sensor.clovelly_rain_chance_0
    internal: true
    on_value:
      then:
        - lvgl.label.update:
            id: rain_chance_label
            text: !lambda |-
              return ("Chance of rain: " + str_sprintf("%.1f", x)).c_str();
