# Designed for Guition ESP32-S3-4848S040
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Esphome
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  area: ${room}

# Over the Air Updates
ota:
  platform: esphome

# Enable Home Assistant API
api:

# Enable logging
logger:

# Video memory
psram:
  mode: octal
  speed: 80MHz

# Backlight Output
output:
  - platform: ledc
    id: backlight_output
    pin: GPIO38
    frequency: 150Hz
    min_power: 0.01
    zero_means_zero: true

# Backlight
light:
  - platform: monochromatic
    name: Backlight
    id: display_backlight
    output: backlight_output
    restore_mode: ALWAYS_ON
    default_transition_length: 1s

# SPI
spi:
  - id: lcd_spi
    clk_pin: GPIO48
    mosi_pin: GPIO47

# Touchscreen I2C
i2c:
  id: touchscreen_bus
  sda: GPIO19
  scl:
    number: 45
    ignore_strapping_warning: true

# Touchscreen
touchscreen:
  - platform: gt911
    id: tft_touch
    display: tft_display

# Display
display:
  - platform: st7701s
    id: tft_display
    dimensions:
      width: 480
      height: 480
    spi_mode: MODE3
    data_rate: 2MHz
    color_order: RGB
    invert_colors: False
    cs_pin: 39
    de_pin: 18
    hsync_pin: 16
    vsync_pin: 17
    pclk_pin: 21
    pclk_frequency: 12MHz
    pclk_inverted: False
    hsync_pulse_width: 8
    hsync_front_porch: 10
    hsync_back_porch: 20
    vsync_pulse_width: 8
    vsync_front_porch: 10
    vsync_back_porch: 10
    update_interval: never
    auto_clear_enabled: False
    init_sequence:
      - 1
      - [0xFF, 0x77, 0x01, 0x00, 0x00, 0x10] # CMD2_BKSEL_BK0
      - [0xCD, 0x00] # disable MDT flag
    data_pins:
      red: [11, 12, 13, 14, 0]
      green: [8, 20, 3, 46, 9, 10]
      blue: [4, 5, 6, 7, 15]